unbind r
bind r source-file ~/.config/tmux/tmux.conf

# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R
unbind-key n
unbind-key p
bind-key l next-window
bind-key h previous-window

unbind-key x
bind-key x kill-pane

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind-key v split-window -h
bind-key s split-window -v

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -g base-index 1
set -g pane-base-index 0
set -sg escape-time 0
set -g mouse on

set-option -g status-position top

set-window-option -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'christoomey/vim-tmux-navigator'


set -g @tokyo-night-tmux_transparent 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
