unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g extended-keys on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Hit Alt + Shift + H to slide the current window left
bind-key H swap-window -t -1\; select-window -t -1

# Hit Alt + Shift + L to slide the current window right
bind-key L swap-window -t +1\; select-window -t +1

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
unbind-key n
unbind-key p

bind-key -n M-L next-window
bind-key -n M-H previous-window

unbind-key x
bind-key x kill-pane

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind-key v split-window -h
bind-key s split-window -v

bind s split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind n new-window -c "#{pane_current_path}"

bind p choose-tree -s

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -g base-index 1
set -g pane-base-index 0
set -sg escape-time 0
set -g mouse on

set-option -g status-position top

set-window-option -g mode-keys vi
setw -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'christoomey/vim-tmux-navigator'


set -g @tokyo-night-tmux_transparent 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
